apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 80
      nodePort: 80 # port of the cluster
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 180610461734.dkr.ecr.eu-west-1.amazonaws.com/weather_app_docker_repository:frontend  
        # 180610461734.dkr.ecr.eu-west-1.amazonaws.com/
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: regcred