apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 9000
      port: 9000
      # nodePort: 30000
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 180610461734.dkr.ecr.eu-west-1.amazonaws.com/weather_app_docker_repository:backend  
        # 180610461734.dkr.ecr.eu-west-1.amazonaws.com/
        ports:
        - containerPort: 9000
      imagePullSecrets:
        - name: regcred